services:
    psql:
        image: postgres:13-alpine
        # build: ./backend/database
        container_name: postgres
        restart: always
        networks:
            - transcendence
        ports:
            - "5439:5432"
        env_file:
            - ./dot_env/.env
        volumes:
            - ./pgdata:/var/lib/postgresql/data/

    backend:
        build: ./backend/docker
        container_name: backend
        volumes:
            - ./backend/:/app/
        ports:
            - "8000:8000"
        networks:
            - transcendence
        restart: on-failure

    frontend:
        build: ./frontend
        container_name: frontend
        volumes:
            - ./frontend/statics/:/usr/share/nginx/html/static/
        ports:
            - "8080:80"
        networks:
            - transcendence
        depends_on:
        - backend

networks:
    transcendence:
        driver: bridge

# volumes:
#   data:
#     driver: local