services:
  backend:
    build: ./backend/docker
    container_name: backend
    volumes:
      - ./backend/:/app/
    ports:
      - "8000:8000"
    networks:
      - transcendence
    command: python3 ./backend/game_server/game_server.py
    restart: on-failure
    depends_on:
      - elasticsearch
      - logstash

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - ./frontend/statics/:/usr/share/nginx/html/static/
    ports:
      - "8080:80"
    networks:
      - transcendence
    depends_on:
      - backend

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - transcendence

  logstash:
    image: docker.elastic.co/logstash/logstash:8.10.2
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    networks:
      - transcendence
    depends_on:
      - elasticsearch

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - transcendence
    depends_on:
      - elasticsearch

networks:
  transcendence:
    driver: bridge

volumes:
  es_data:
    driver: local
