filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/django/*.log
  # json.keys_under_root: true
  # json.add_error_key: true
  # tags: ["app-logs"]

- type: log
  enabled: true
  paths:
    - /var/log/nginx/*.log
  # tags: ["nginx-logs"]
  # multiline:
  #   pattern: '^\d{4}/\d{2}/\d{2}'
  #   negate: true
  #   match: after

output.logstash:
  hosts: ["logstash:5044"]

logging.level: debug

setup.ilm.enabled: true

